# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProyectoCovid19' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProyectoCovid19
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 5.2'
  pod 'Charts'
  pod 'GoogleMaps'
  pod 'UTMConversion', '~> 1.3'
end
